function [info] = get_info(varargin)
% This function returns the default `info` structure with the fields:
%
% struct("thresh", 8, "smooth", 0.5, "N", 0.05, ...
%     "diss_length", 1024, "f_AA", 98, "f_limit", Inf, "fft_length", 512, ...
%     "fit_2_isr", 1.5e-5, "fit_order", 3, "goodman", true, ...
%     "overlap", 512, "pMin", 5, "wMin", 0.5, "minDuration", 10, ...
%     "chop_end", "bottom", "overwrite", false)
%
% See help for despike, get_profile or get_diss_odas to learn the what the
% fields are.
%
% First created by Jesse Cusack (jesse.cusack@oregonstate.edu) 2023-06-02.

info = struct("thresh", 8, "smooth", 0.5, "N", 0.05, ...
       "diss_length", 1024, "f_AA", 98, "f_limit", Inf, "fft_length", 512, ...
       "fit_2_isr", 1.5e-5, "fit_order", 3, "goodman", true, ...
       "overlap", 512, "pMin", 5, "wMin", 0.5, "minDuration", 10, ...
       "chop_end", "bottom", "overwrite", false);

end